version: "3.8"

services:
  yocto:
    image: "yocto"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/home/dev/src
      - build_data:/home/dev/build

volumes:
  build_data:
